---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, BlueXP, bluexp, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention, netapp replication 
summary: NetApp SnapMirror repliziert Daten mit hoher Geschwindigkeit über LAN oder WAN, sodass Sie sowohl in virtuellen als auch in herkömmlichen Umgebungen eine hohe Datenverfügbarkeit und schnelle Datenreplikation erzielen.  Wenn Sie Daten auf NetApp -Speichersysteme replizieren und die sekundären Daten kontinuierlich aktualisieren, bleiben Ihre Daten aktuell und stehen Ihnen jederzeit zur Verfügung. Es sind keine externen Replikationsserver erforderlich. 
---
= Erfahren Sie mehr über NetApp Replication
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror repliziert Daten mit hoher Geschwindigkeit über LAN oder WAN, sodass Sie sowohl in virtuellen als auch in herkömmlichen Umgebungen eine hohe Datenverfügbarkeit und schnelle Datenreplikation erzielen.  Wenn Sie Daten mithilfe von NetApp Replication auf NetApp -Speichersysteme replizieren und die sekundären Daten kontinuierlich aktualisieren, bleiben Ihre Daten aktuell und stehen Ihnen jederzeit zur Verfügung. Es sind keine externen Replikationsserver erforderlich.



[[netapp-console]]
== NetApp Console

Auf NetApp Replication kann über die NetApp Console zugegriffen werden.

Die NetApp Console ermöglicht die zentrale Verwaltung von NetApp Speicher- und Datendiensten in lokalen und Cloud-Umgebungen auf der Enterprise-Klasse. Die Console ist für den Zugriff auf und die Nutzung von NetApp Datendiensten erforderlich. Als Managementoberfläche ermöglicht sie die Verwaltung zahlreicher Speicherressourcen über eine einzige Oberfläche. Konsolenadministratoren können den Zugriff auf Speicher und Dienste für alle Systeme im Unternehmen steuern.

Sie benötigen weder eine Lizenz noch ein Abonnement, um die NetApp Console zu verwenden. Es fallen nur dann Kosten an, wenn Sie Konsolenagenten in Ihrer Cloud bereitstellen müssen, um die Konnektivität zu Ihren Speichersystemen oder NetApp -Datendiensten sicherzustellen. Einige NetApp -Datendienste, auf die über die Konsole zugegriffen werden kann, sind jedoch lizenz- oder abonnementbasiert.

Erfahren Sie mehr über das  https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console"].



[[features]]
== Features

* Replizieren Sie Daten zwischen ONTAP Speichersystemen, um Backup und Disaster Recovery in der Cloud oder zwischen Clouds zu unterstützen.
* Stellen Sie die Zuverlässigkeit Ihrer DR-Umgebung mit hoher Verfügbarkeit sicher.
* Die effiziente Replikation auf Blockebene zwischen ONTAP -Speicher ist schnell und effizient und bietet granulare Wiederherstellungspunkte für DR und Backup.




[[cost]]
== Kosten

NetApp berechnet Ihnen für die Nutzung von NetApp Replication keine Gebühren, Sie müssen sich jedoch bei Ihrem Cloud-Anbieter über die anfallenden Gebühren für den Dateneingang und -ausgang informieren.



[[supported-systems]]
== Unterstützte Systeme

NetApp Replication ermöglicht die Datenreplikation zwischen den folgenden Systemtypen.

[cols="30,30"]
|===
| Quellsystem | Unterstützte Zielsysteme 


| Cloud Volumes ONTAP  a| 
* Amazon FSx für ONTAP
* Cloud Volumes ONTAP
* On-Premises ONTAP Cluster




| On-Premises ONTAP Cluster  a| 
* Amazon FSx für ONTAP
* Cloud Volumes ONTAP
* On-Premises ONTAP Cluster




| Amazon FSx für ONTAP  a| 
* Amazon FSx für ONTAP
* Cloud Volumes ONTAP
* On-Premises ONTAP Cluster


|===


[[how-data-replication-works]]
== So funktioniert die Datenreplikation

NetApp Replication vereinfacht die Datenreplikation zwischen Volumes auf separaten ONTAP Systemen mithilfe der Technologien SnapMirror und SnapVault .  Sie müssen lediglich das Quellvolume und das Zielvolume identifizieren und dann eine Replikationsrichtlinie und einen Zeitplan auswählen.

Für Cloud Volumes ONTAP kauft NetApp Replication die erforderlichen Festplatten, konfiguriert Beziehungen, wendet die Replikationsrichtlinie an und leitet dann die Basisübertragung zwischen den Volumes ein.


NOTE: Die Basisübertragung umfasst eine vollständige Kopie der Quelldaten.  Nachfolgende Übertragungen enthalten differenzielle Kopien der Quelldaten.



[[supported-data-protection-configurations]]
== Unterstützte Datenschutzkonfigurationen

NetApp Replication unterstützt einfache, Fanout- und kaskadierte Datenschutzkonfigurationen:

* In einer einfachen Konfiguration erfolgt die Replikation von Volume A nach Volume B.
* In einer Fanout-Konfiguration erfolgt die Replikation von Volume A zu mehreren Zielen.
* In einer Kaskadenkonfiguration erfolgt die Replikation von Volume A zu Volume B und von Volume B zu Volume C.




[[replicate-data-using-netapp-backup-and-recovery]]
== Datenreplikation mit NetApp Backup and Recovery

Ab der Version 3.9.31 des NetApp Console-Agenten ermöglicht NetApp Backup and Recovery die Replikation von Daten zwischen Volumes auf separaten ONTAP-Systemen mithilfe der SnapMirror- und SnapVault-Technologien. Wenn eine Replikation von Daten auf andere ONTAP-Systeme sowie die Erstellung von Backups derselben Daten im Objektspeicher vorgesehen ist, kann  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recovery"^] genutzt werden, um den Schutzbedarf der Daten mit einem einzigen Service zu verwalten.

NetApp Backup and Recovery unterstützt die folgende Funktionalität nicht, die in NetApp Replication verfügbar ist:

* Eine Kaskadenkonfiguration, bei der die Replikation von Volume A zu Volume B und dann von Volume B zu Volume C erfolgt, wird nicht unterstützt.
* Es gibt keine Unterstützung für die Replikation von Daten zu oder von FSx für ONTAP -Systeme.
* Das Erstellen einer einmaligen Replikation eines Volumes wird nicht unterstützt.


Wenn Sie also eine dieser Funktionen benötigen, verwenden Sie NetApp Replication.
