---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, BlueXP, bluexp, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention, netapp replication 
summary: NetApp SnapMirror repliziert Daten mit hoher Geschwindigkeit über LAN oder WAN, sodass Sie sowohl in virtuellen als auch in herkömmlichen Umgebungen eine hohe Datenverfügbarkeit und schnelle Datenreplikation erzielen.  Wenn Sie Daten auf NetApp -Speichersysteme replizieren und die sekundären Daten kontinuierlich aktualisieren, bleiben Ihre Daten aktuell und stehen Ihnen jederzeit zur Verfügung. Es sind keine externen Replikationsserver erforderlich. 
---
= Erfahren Sie mehr über NetApp Replication
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror repliziert Daten mit hoher Geschwindigkeit über LAN oder WAN, sodass Sie sowohl in virtuellen als auch in herkömmlichen Umgebungen eine hohe Datenverfügbarkeit und schnelle Datenreplikation erzielen.  Wenn Sie Daten mithilfe von NetApp Replication auf NetApp -Speichersysteme replizieren und die sekundären Daten kontinuierlich aktualisieren, bleiben Ihre Daten aktuell und stehen Ihnen jederzeit zur Verfügung. Es sind keine externen Replikationsserver erforderlich.



[[netapp-console]]
== NetApp Console

Auf NetApp Replication kann über die NetApp Console zugegriffen werden.

Die Konsole ermöglicht die zentrale Verwaltung von NetApp Speicher- und Datendiensten in lokalen und Cloud-Umgebungen auf der Enterprise-Klasse. Die Konsole ist für den Zugriff auf und die Nutzung von NetApp Datendiensten erforderlich. Als Managementoberfläche ist die Verwaltung zahlreicher Speicherressourcen über eine einzige Oberfläche möglich. Konsolenadministratoren können den Zugriff auf Speicher und Dienste für alle Systeme im Unternehmen steuern.

Für die Nutzung der Konsole benötigen Sie weder eine Lizenz noch ein Abonnement. Kosten fallen nur dann an, wenn Sie Konsolenagenten in Ihrer Cloud bereitstellen müssen, um die Verbindung zu Ihren Speichersystemen oder NetApp Datenservices sicherzustellen. Einige NetApp Datenservices, die über die Konsole zugänglich sind, sind jedoch lizenz- oder abonnementbasiert.

Erfahren Sie mehr über das  https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console"].



[[features]]
== Features

* Replizieren Sie Daten zwischen ONTAP Speichersystemen, um Backup und Disaster Recovery in der Cloud oder zwischen Clouds zu unterstützen.
* Stellen Sie die Zuverlässigkeit Ihrer DR-Umgebung mit hoher Verfügbarkeit sicher.
* Die effiziente Block-Level-Replikation zwischen ONTAP-Speichersystemen ist schnell und effizient, mit granularen Wiederherstellungspunkten sowohl für die Notfallwiederherstellung als auch für die Datensicherung.




[[cost]]
== Kosten

NetApp berechnet Ihnen für die Nutzung von NetApp Replication keine Gebühren, Sie müssen sich jedoch bei Ihrem Cloud-Anbieter über die anfallenden Gebühren für den Dateneingang und -ausgang informieren.



[[supported-systems]]
== Unterstützte Systeme

NetApp Replication ermöglicht die Datenreplikation zwischen den folgenden Systemtypen.

[cols="30,30"]
|===
| Quellsystem | Unterstützte Zielsysteme 


| Cloud Volumes ONTAP  a| 
* Amazon FSx für ONTAP
* Cloud Volumes ONTAP
* On-Premises ONTAP Cluster




| On-Premises ONTAP Cluster  a| 
* Amazon FSx für ONTAP
* Cloud Volumes ONTAP
* On-Premises ONTAP Cluster




| Amazon FSx für ONTAP  a| 
* Amazon FSx für ONTAP
* Cloud Volumes ONTAP
* On-Premises ONTAP Cluster


|===


[[how-data-replication-works]]
== So funktioniert die Datenreplikation

NetApp Replication vereinfacht die Datenreplizierung zwischen Volumes auf separaten ONTAP Systemen mithilfe der SnapMirror und SnapVault Technologien. Für die Konfiguration der Replikation ist es lediglich erforderlich, das Quellvolume und das Zielvolume zu identifizieren und anschließend eine Replikationsrichtlinie sowie einen Zeitplan auszuwählen.

Für Cloud Volumes ONTAP kauft NetApp Replication die erforderlichen Festplatten, konfiguriert Beziehungen, wendet die Replikationsrichtlinie an und leitet dann die Basisübertragung zwischen den Volumes ein.


NOTE: Die Basisübertragung umfasst eine vollständige Kopie der Quelldaten.  Nachfolgende Übertragungen enthalten differenzielle Kopien der Quelldaten.



[[supported-data-protection-configurations]]
== Unterstützte Datenschutzkonfigurationen

NetApp Replication unterstützt einfache, Fanout- und kaskadierte Datenschutzkonfigurationen:

* In einer einfachen Konfiguration erfolgt die Replikation von Volume A nach Volume B.
* In einer Fanout-Konfiguration erfolgt die Replikation von Volume A zu mehreren Zielen.
* In einer Kaskadenkonfiguration erfolgt die Replikation von Volume A zu Volume B und von Volume B zu Volume C.




[[replicate-data-using-netapp-backup-and-recovery]]
== Datenreplikation mit NetApp Backup and Recovery

link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recovery"^]ermöglicht die Replizierung von Daten zwischen Volumes auf separaten ONTAP Systemen und gleichzeitig die Erstellung von Backups derselben Daten im Objektspeicher. Wenn sowohl die Datenreplizierung als auch der Backup-to-Object-Schutz für dieselben ONTAP Daten in einem einzigen Service verwaltet werden sollen, bietet sich NetApp Backup and Recovery an.

NetApp Replication unterstützt die folgenden Funktionen, die in Backup and Recovery nicht verfügbar sind.

* Backup and Recovery unterstützt derzeit keine Replikation von Daten zu oder von FSx for ONTAP Systemen.
* Backup and Recovery unterstützt das Erstellen einer einmaligen Replikation eines Volumes nicht.


Darüber hinaus lassen sich Kaskadenbeziehungen in Replication einfacher konfigurieren. Falls eine dieser Funktionen benötigt wird, empfiehlt sich NetApp Replication.
