---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, releases' 
summary: Erfahren Sie, was es Neues bei NetApp Replication gibt. 
---
= Was ist neu bei NetApp Replication?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie, was es Neues bei NetApp Replication gibt.



[[13-april-2026]]
== 13. April 2026



[[replication-management-for-existing-relationships-with-fsx-for-ontap]]
=== Replikationsmanagement für bestehende Beziehungen mit FSx für ONTAP

Die Replikationsbeziehungsverwaltung für FSx for ONTAP-Dateisysteme als Quelle oder Ziel befindet sich jetzt in NetApp Workload Factory.

link:https://docs.netapp.com/us-en/data-services-replication/task-managing-replication.html["Verwalten der Datenreplikation"]



[[06-october-2025]]
== 06. Oktober 2025



[[bluexp-replication-is-now-netapp-replication]]
=== BlueXP replication heißt jetzt NetApp Replication

Die BlueXP replication wurde in NetApp Replication umbenannt.



[[bluexp-is-now-netapp-console]]
=== BlueXP heißt jetzt NetApp Console

Die NetApp Console basiert auf der verbesserten und neu strukturierten BlueXP -Grundlage und ermöglicht die zentrale Verwaltung von NetApp -Speicher und NetApp Data Services in On-Premises- und Cloud-Umgebungen auf Unternehmensniveau. Sie liefert Einblicke in Echtzeit, schnellere Arbeitsabläufe und eine vereinfachte Verwaltung mit hoher Sicherheit und Konformität.

Einzelheiten zu den Änderungen sind im Abschnitt link:https://docs.netapp.com/us-en/console-relnotes/index.html["Versionshinweise zur NetApp Console"] zu finden.



[[18-september-2022]]
== 18. September 2022



[[fsx-for-ontap-to-cloud-volumes-ontap]]
=== FSx für ONTAP zu Cloud Volumes ONTAP

Sie können jetzt Daten von einem Amazon FSx for ONTAP -Dateisystem auf Cloud Volumes ONTAP replizieren.

link:https://docs.netapp.com/us-en/data-services-replication/task-replicating-data.html["Erfahren Sie, wie Sie die Datenreplikation einrichten"].



[[31-july-2022]]
== 31. Juli 2022



[[fsx-for-ontap-as-the-data-source]]
=== FSx for ONTAP als Datenquelle

Sie können jetzt Daten von einem Amazon FSx for ONTAP -Dateisystem an die folgenden Ziele replizieren:

* Amazon FSx für ONTAP
* On-Premises- ONTAP -Cluster


link:https://docs.netapp.com/us-en/data-services-replication/task-replicating-data.html["Erfahren Sie, wie Sie die Datenreplikation einrichten"].



[[02-september-2021]]
== 02. September 2021



[[support-for-amazon-fsx-for-ontap]]
=== Support für Amazon FSx für ONTAP

Sie können jetzt Daten von einem Cloud Volumes ONTAP -System oder einem lokalen ONTAP Cluster auf ein Amazon FSx für ONTAP Dateisystem replizieren.

link:https://docs.netapp.com/us-en/data-services-replication/task-replicating-data.html["Erfahren Sie, wie Sie die Datenreplikation einrichten"].



[[05-may-2021]]
== 05. Mai 2021



[[redesigned-interface]]
=== Neu gestaltete Benutzeroberfläche

Wir haben die Replikation neu gestaltet, um sie benutzerfreundlicher zu gestalten und sie an das aktuelle Erscheinungsbild der Benutzeroberfläche anzupassen.
